version: '3.8'

services:
  fastapi:
    build: .
    volumes:
      - ./qr_codes:/home/hemanjali/qr_codes  # Ensure this directory exists on the host and has appropriate permissions
    environment:
      - QR_DIRECTORY=/home/hemanjali/qr_codes
      - FILL_COLOR=red
      - BACK_COLOR=white
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./qr_codes:/var/www/qr_codes  # Ensure correct permissions
