name: AWS Deployment

on:
  push:
    branches:
      - main
    paths:
      - '**.py'
      - '.github/workflows/aws-actions.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::123456789012:role/GitHubActionsRole
        role-duration-seconds: 1200
        role-session-name: GitHubActionsSession

    - name: Deploy to AWS
      run: |
        # Example command; replace with your AWS deployment commands
        aws s3 cp my-file.txt s3://my-bucket/
