name: Python application test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
      build-and-test:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - name: Set up Python
            uses: actions/setup-python@v2
            with:
              python-version: '3.10'
          - name: Install Dependencies
            run: pip install -r requirements.txt
          - name: Run Tests
            run: pytest -s
          - name: Upload Artifacts
            if: failure()  # Only upload if the workflow fails
            uses: actions/upload-artifact@v2
            with:
              name: logs
              path: path/to/logs  # Specify the path to any logs or files you want to examine
    
    
