name: AWS Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: your-region
          role-to-assume: your-role-arn
          role-duration-seconds: 3600
          role-session-name: GitHubActionsSession
          role-skip-session-tagging: false
          audience: sts.amazonaws.com

      - name: Deploy to AWS
        run: |
          # Your AWS CLI commands or deployment scripts
          echo "Deploying to AWS..."
          # Example: Upload a file to an S3 bucket
          aws s3 cp ./your-file.txt s3://your-bucket-name/
