name: AWS Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: your-region  # Specify your AWS region
        role-to-assume: your-role-arn  # ARN of the role to assume
        role-duration-seconds: 3600  # Session duration in seconds
        role-session-name: GitHubActionsSession  # Optional session name
        role-skip-session-tagging: false  # Tags the session with GitHub Actions info if true
        audience: sts.amazonaws.com  # The intended recipient of the credentials

    - name: Additional AWS Actions
      run: |
        # Your AWS CLI commands or scripts that use AWS credentials
        aws s3 ls

    - name: Clean up Actions
      if: always()
      run: |
        # Any cleanup tasks or final steps
        echo "Clean up complete"
